[theme]
#primaryColor="#F63366"
primaryColor="#47C7DA"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"

[browser]
gatherUsageStats = true

[client]
toolbarMode = "developer"
